/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ideas_anima_engine_gameplay_physics_Body */

#ifndef _Included_com_ideas_anima_engine_gameplay_physics_Body
#define _Included_com_ideas_anima_engine_gameplay_physics_Body
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ideas_anima_engine_gameplay_physics_Body
 * Method:    getBodyPointer
 * Signature: (IJF)J
 */
JNIEXPORT jlong JNICALL Java_com_ideas_anima_engine_gameplay_physics_Body_getBodyPointer
  (JNIEnv *, jobject, jint, jlong, jfloat, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
