/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ideas_anima_engine_gameplay_physics_SphereShape */

#ifndef _Included_com_ideas_anima_engine_gameplay_physics_SphereShape
#define _Included_com_ideas_anima_engine_gameplay_physics_SphereShape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ideas_anima_engine_gameplay_physics_SphereShape
 * Method:    getSphereShapePointer
 * Signature: (F)J
 */
JNIEXPORT jlong JNICALL Java_com_ideas_anima_engine_gameplay_physics_SphereShape_getSphereShapePointer
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
