/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ideas_anima_engine_gameplay_physics_ConeShape */

#ifndef _Included_com_ideas_anima_engine_gameplay_physics_ConeShape
#define _Included_com_ideas_anima_engine_gameplay_physics_ConeShape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ideas_anima_engine_gameplay_physics_ConeShape
 * Method:    getConeShapePointer
 * Signature: (FF)J
 */
JNIEXPORT jlong JNICALL Java_com_ideas_anima_engine_gameplay_physics_ConeShape_getConeShapePointer
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
