/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ideas_anima_engine_gameplay_physics_CylinderShape */

#ifndef _Included_com_ideas_anima_engine_gameplay_physics_CylinderShape
#define _Included_com_ideas_anima_engine_gameplay_physics_CylinderShape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ideas_anima_engine_gameplay_physics_CylinderShape
 * Method:    getCylinderShapePointer
 * Signature: (FFF)J
 */
JNIEXPORT jlong JNICALL Java_com_ideas_anima_engine_gameplay_physics_CylinderShape_getCylinderShapePointer
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
