/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ideas_anima_engine_gameplay_physics_BoxShape */

#ifndef _Included_com_ideas_anima_engine_gameplay_physics_BoxShape
#define _Included_com_ideas_anima_engine_gameplay_physics_BoxShape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ideas_anima_engine_gameplay_physics_BoxShape
 * Method:    getBoxShapePointer
 * Signature: (FFF)J
 */
JNIEXPORT jlong JNICALL Java_com_ideas_anima_engine_gameplay_physics_BoxShape_getBoxShapePointer
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
