/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ideas_anima_engine_gameplay_physics_CompoundShape */

#ifndef _Included_com_ideas_anima_engine_gameplay_physics_CompoundShape
#define _Included_com_ideas_anima_engine_gameplay_physics_CompoundShape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ideas_anima_engine_gameplay_physics_CompoundShape
 * Method:    getCompoundShapePointer
 * Signature: ([J[Lcom/ideas/anima/engine/graphics/Vector;)J
 */
JNIEXPORT jlong JNICALL Java_com_ideas_anima_engine_gameplay_physics_CompoundShape_getCompoundShapePointer
  (JNIEnv *, jobject, jlongArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
