/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ideas_anima_engine_gameplay_physics_CapsuleShape */

#ifndef _Included_com_ideas_anima_engine_gameplay_physics_CapsuleShape
#define _Included_com_ideas_anima_engine_gameplay_physics_CapsuleShape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ideas_anima_engine_gameplay_physics_CapsuleShape
 * Method:    getCapsuleShapePointer
 * Signature: (FF)J
 */
JNIEXPORT jlong JNICALL Java_com_ideas_anima_engine_gameplay_physics_CapsuleShape_getCapsuleShapePointer
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
